# Default values for gitea.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

moduleId: ""
username: ""
password: ""

route:
  enabled: false

gitea:
  ingress:
    enabled: false
    hosts:
      - host: git.example.com
        paths:
          - path: /
            pathType: Prefix
        tls:
          - secretName: tls-secret-name
            hosts:
              - git.example.com
