apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-module" .Release.Name }}
  labels:
    {{ include "gitea.labels" . | nindent 4 }}
data:
  moduleId: {{ required "moduleId must be provided" .Values.moduleId | quote }}
