apiVersion: v1
kind: Secret
metadata:
  name: {{ "%s-admin" (include "gitea.name" .) }}
  labels:
    {{ include "gitea.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.username }}
  password: {{ .Values.password }}
