{{- if and .Values.route .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: git
  labels:
    {{- include "gitea.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
  to:
    kind: Service
    name: {{ printf "%s-http" .Release.Name }}
{{- end }}
