apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-pvc-delete" .Release.Name }}
  labels:
    {{ include "gitea.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
